"""initial migration

Revision ID: 373af81684f9
Revises: 51f5ccfba190
Create Date: 2016-02-24 14:12:17.832875

"""

# revision identifiers, used by Alembic.
revision = '373af81684f9'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
