"""initial migration

Revision ID: 3c31860522aa
Revises: 373af81684f9
Create Date: 2016-02-24 14:12:28.147712

"""

# revision identifiers, used by Alembic.
revision = '3c31860522aa'
down_revision = '373af81684f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
